# Week 1 - Data Ingestion

## Objective

The objective of this notebook is to import the raw marketing attribution dataset, inspect its structure, understand the available features, and prepare the data for cleaning and analysis.

### Dataset
- multi_touch_attribution_data.csv

### Tasks
- Load Dataset
- Inspect Shape
- View Columns
- Check Data Types
- Display Sample Records

In [1]:
import pandas as pd
import numpy as np

# Display all columns
pd.set_option("display.max_columns", None)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [2]:
df = pd.read_csv("../data/raw/multi_touch_attribution_data.csv")

In [3]:
df.shape

(10000, 5)

In [4]:
df.head()

   User ID            Timestamp         Channel            Campaign Conversion
0    83281  2025-02-10 07:58:51           Email  New Product Launch         No
1    68071  2025-02-10 23:38:48      Search Ads         Winter Sale         No
2    90131  2025-02-11 10:41:07    Social Media     Brand Awareness        Yes
3    71026  2025-02-10 08:19:44  Direct Traffic                   -        Yes
4    94486  2025-02-10 15:15:46           Email         Retargeting        Yes

In [5]:
df.columns

Index(['User ID', 'Timestamp', 'Channel', 'Campaign', 'Conversion'], dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   User ID     10000 non-null  int64
 1   Timestamp   10000 non-null  str
 2   Channel     10000 non-null  str
 3   Campaign    10000 non-null  str
 4   Conversion  10000 non-null  str
dtypes: int64(1), str(4)
memory usage: 390.8 KB

In [7]:
attribution = pd.read_csv("../data/raw/multi_touch_attribution_data.csv")

performance = pd.read_csv("../data/raw/tech_advertising_campaigns_dataset.csv")

In [8]:
attribution.shape
performance.shape

(10000, 41)

In [9]:
attribution.head()
performance.head()

,campaign_id,campaign_objective,platform,ad_placement,device_type,operating_system,creative_format,creative_size,ad_copy_length,has_call_to_action,creative_emotion,creative_age_days,target_audience_age,target_audience_gender,audience_interest_category,income_bracket,purchase_intent_score,retargeting_flag,start_date,quarter,day_of_week,hour_of_day,campaign_day,quality_score,actual_cpc,impressions,clicks,conversions,ad_spend,revenue,bounce_rate,avg_session_duration_seconds,pages_per_session,industry_vertical,budget_tier,CTR,CPC,conversion_rate,CPA,ROAS,profit
0,CAMP_00001,Lead Generation,Facebook,Search,Mobile,Android,Text,728x90,Short,False,Curiosity,72,45-54,Female,Shoppers,<$50K,Medium,False,2024-03-06,1,Wednesday,18,34,5,2.23,66329,402,2,896.46,289.67,67.75,70,2.00,E-commerce,High,0.606,2.23,0.498,448.23,0.32,-606.79
1,CAMP_00002,Engagement,Facebook,Feed,Mobile,iOS,Image,320x50,Long,True,Neutral,62,65+,Female,Business Professionals,$50K-$100K,Medium,False,2024-01-26,1,Friday,6,22,5,2.48,50094,467,5,1158.16,1728.20,63.73,105,2.74,Finance,Medium,0.932,2.48,1.071,231.63,1.49,570.04
2,CAMP_00003,Conversions,Google Ads,Feed,Tablet,iOS,Video,1920x1080,Short,False,Urgency,79,65+,Male,Tech Enthusiasts,<$50K,High,False,2025-05-15,2,Thursday,1,32,4,3.88,10842,112,6,434.56,2903.26,31.93,149,3.97,Healthcare,Low,1.033,3.88,5.357,72.43,6.68,2468.70
3,CAMP_00004,Conversions,LinkedIn,Search,Desktop,iOS,Carousel,1920x1080,Short,False,Joy,57,35-44,All,Shoppers,<$50K,Low,False,2024-07-21,3,Sunday,7,32,4,8.29,7820,123,3,1019.67,502.28,65.52,147,2.49,Education,Medium,1.573,8.29,2.439,339.89,0.49,-517.39
4,CAMP_00005,Brand Awareness,Facebook,Stories,Mobile,iOS,Image,1920x1080,Short,False,Joy,17,25-34,Female,Students,$100K-$200K,Low,False,2025-03-09,1,Sunday,17,52,7,1.41,21436,302,0,425.82,0.00,68.95,81,3.04,SaaS,Low,1.409,1.41,0.000,0.00,0.00,-425.82

In [10]:
attribution.columns
performance.columns

Index(['campaign_id', 'campaign_objective', 'platform', 'ad_placement',
       'device_type', 'operating_system', 'creative_format', 'creative_size',
       'ad_copy_length', 'has_call_to_action', 'creative_emotion',
       'creative_age_days', 'target_audience_age', 'target_audience_gender',
       'audience_interest_category', 'income_bracket', 'purchase_intent_score',
       'retargeting_flag', 'start_date', 'quarter', 'day_of_week',
       'hour_of_day', 'campaign_day', 'quality_score', 'actual_cpc',
       'impressions', 'clicks', 'conversions', 'ad_spend', 'revenue',
       'bounce_rate', 'avg_session_duration_seconds', 'pages_per_session',
       'industry_vertical', 'budget_tier', 'CTR', 'CPC', 'conversion_rate',
       'CPA', 'ROAS', 'profit'],
      dtype='str')

In [11]:
attribution.info()
performance.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   User ID     10000 non-null  int64
 1   Timestamp   10000 non-null  str
 2   Channel     10000 non-null  str
 3   Campaign    10000 non-null  str
 4   Conversion  10000 non-null  str
dtypes: int64(1), str(4)
memory usage: 390.8 KB
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 41 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   campaign_id                   10000 non-null  str
 1   campaign_objective            10000 non-null  str
 2   platform                      10000 non-null  str
 3   ad_placement                  10000 non-null  str
 4   device_type                   10000 non-null  str
 5   operating_system              10000 non-null  str
 6   creative_format               10000 non-null  str
 7   creative_size                 10000 non-null  str
 8   ad_copy_length                10000 non-null  str
 9   has_call_to_action            10000 non-null  bool
 10  creative_emotion              10000 non-null  str
 11  creative_age_days             10000 non-null  int64
 12  target_audience_age           10000 non-null  str
 13  target_audience_gender        10000 non-null  str
 14  audience_interest_category    10000 non-null  str
 15  income_bracket                10000 non-null  str
 16  purchase_intent_score         10000 non-null  str
 17  retargeting_flag              10000 non-null  bool
 18  start_date                    10000 non-null  str
 19  quarter                       10000 non-null  int64
 20  day_of_week                   10000 non-null  str
 21  hour_of_day                   10000 non-null  int64
 22  campaign_day                  10000 non-null  int64
 23  quality_score                 10000 non-null  int64
 24  actual_cpc                    10000 non-null  float64
 25  impressions                   10000 non-null  int64
 26  clicks                        10000 non-null  int64
 27  conversions                   10000 non-null  int64
 28  ad_spend                      10000 non-null  float64
 29  revenue                       10000 non-null  float64
 30  bounce_rate                   10000 non-null  float64
 31  avg_session_duration_seconds  10000 non-null  int64
 32  pages_per_session             10000 non-null  float64
 33  industry_vertical             10000 non-null  str
 34  budget_tier                   10000 non-null  str
 35  CTR                           10000 non-null  float64
 36  CPC                           10000 non-null  float64
 37  conversion_rate               10000 non-null  float64
 38  CPA                           10000 non-null  float64
 39  ROAS                          10000 non-null  float64
 40  profit                        10000 non-null  float64
dtypes: bool(2), float64(11), int64(9), str(19)
memory usage: 3.0 MB

# Data Quality Assessment

## Objective

Before preprocessing, we evaluate the quality of the datasets by checking:

- Missing Values
- Duplicate Records
- Data Types
- Unique Values
- Statistical Summary

This helps identify potential issues that may affect downstream analysis.

In [12]:
print("Attribution Dataset")
display(attribution.isnull().sum())

print("\nPerformance Dataset")
display(performance.isnull().sum())

Attribution Dataset

User ID       0
Timestamp     0
Channel       0
Campaign      0
Conversion    0
dtype: int64

Performance Dataset

campaign_id                     0
campaign_objective              0
platform                        0
ad_placement                    0
device_type                     0
operating_system                0
creative_format                 0
creative_size                   0
ad_copy_length                  0
has_call_to_action              0
creative_emotion                0
creative_age_days               0
target_audience_age             0
target_audience_gender          0
audience_interest_category      0
income_bracket                  0
purchase_intent_score           0
retargeting_flag                0
start_date                      0
quarter                         0
day_of_week                     0
hour_of_day                     0
campaign_day                    0
quality_score                   0
actual_cpc                      0
impressions                     0
clicks                          0
conversions                     0
ad_spend                        0
revenue                         0
bounce_rate                     0
avg_session_duration_seconds    0
pages_per_session               0
industry_vertical               0
budget_tier                     0
CTR                             0
CPC                             0
conversion_rate                 0
CPA                             0
ROAS                            0
profit                          0
dtype: int64

In [13]:
print("Attribution Duplicates :", attribution.duplicated().sum())
print("Performance Duplicates :", performance.duplicated().sum())

Attribution Duplicates : 0
Performance Duplicates : 0

In [14]:
attribution.dtypes

User ID       int64
Timestamp       str
Channel         str
Campaign        str
Conversion      str
dtype: object

In [15]:
performance.dtypes

campaign_id                         str
campaign_objective                  str
platform                            str
ad_placement                        str
device_type                         str
operating_system                    str
creative_format                     str
creative_size                       str
ad_copy_length                      str
has_call_to_action                 bool
creative_emotion                    str
creative_age_days                 int64
target_audience_age                 str
target_audience_gender              str
audience_interest_category          str
income_bracket                      str
purchase_intent_score               str
retargeting_flag                   bool
start_date                          str
quarter                           int64
day_of_week                         str
hour_of_day                       int64
campaign_day                      int64
quality_score                     int64
actual_cpc                      float64
impressions                       int64
clicks                            int64
conversions                       int64
ad_spend                        float64
revenue                         float64
bounce_rate                     float64
avg_session_duration_seconds      int64
pages_per_session               float64
industry_vertical                   str
budget_tier                         str
CTR                             float64
CPC                             float64
conversion_rate                 float64
CPA                             float64
ROAS                            float64
profit                          float64
dtype: object

In [16]:
print(attribution["Channel"].value_counts())

Channel
Direct Traffic    1721
Referral          1685
Display Ads       1669
Social Media      1662
Email             1654
Search Ads        1609
Name: count, dtype: int64

In [17]:
print(attribution["Campaign"].value_counts())

Campaign
-                     3131
New Product Launch    1416
Retargeting           1379
Brand Awareness       1378
Winter Sale           1372
Discount Offer        1324
Name: count, dtype: int64

In [18]:
performance.describe()

,creative_age_days,quarter,hour_of_day,campaign_day,quality_score,actual_cpc,impressions,clicks,conversions,ad_spend,revenue,bounce_rate,avg_session_duration_seconds,pages_per_session,CTR,CPC,conversion_rate,CPA,ROAS,profit
count,10000.0000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,1.000000e+04
mean,45.3743,2.419100,11.482500,45.429700,5.527400,3.290336,70539.223000,1526.436100,65.568800,4345.566179,2.841577e+04,52.528500,100.956600,3.113223,2.314340,3.290336,3.644033,190.895894,7.524918,2.407020e+04
std,26.1711,1.132424,6.932308,26.071107,1.553541,2.453852,91339.733246,2412.164582,183.404876,6917.481037,8.928461e+04,17.706165,46.541295,1.369884,1.573316,2.453852,4.354338,295.614462,14.985237,8.641610e+04
min,1.0000,1.000000,0.000000,1.000000,1.000000,0.300000,5000.000000,10.000000,0.000000,8.690000,0.000000e+00,10.000000,10.000000,1.000000,0.100000,0.300000,0.000000,0.000000,0.000000,-3.693984e+04
25%,22.0000,1.000000,5.000000,23.000000,4.000000,1.510000,16958.500000,290.000000,5.000000,666.307500,1.608910e+03,40.087500,68.000000,2.160000,1.172000,1.510000,1.005000,40.640000,1.197500,2.094800e+02
50%,45.0000,2.000000,12.000000,45.000000,6.000000,2.430000,37469.500000,718.000000,16.000000,1895.670000,6.099240e+03,53.580000,100.000000,2.830000,1.920000,2.430000,2.165500,99.460000,3.150000,3.302535e+03
75%,68.0000,3.000000,18.000000,68.000000,7.000000,4.530000,83213.750000,1746.000000,55.000000,4996.160000,2.216582e+04,65.472500,132.000000,3.740000,3.017250,4.530000,4.493250,225.457500,7.950000,1.664188e+04
max,90.0000,4.000000,23.000000,90.000000,10.000000,16.030000,500000.000000,40000.000000,5384.000000,49999.680000,2.800397e+06,90.000000,277.000000,8.510000,8.000000,16.030000,25.000000,6379.940000,487.300000,2.750398e+06