# Week 1 - Data Ingestion

## Objective

The objective of this notebook is to import the raw marketing attribution dataset, inspect its structure, understand the available features, and prepare the data for cleaning and analysis.

### Dataset
- multi_touch_attribution_data.csv

### Tasks
- Load Dataset
- Inspect Shape
- View Columns
- Check Data Types
- Display Sample Records

In [1]:
import pandas as pd
import numpy as np

# Display all columns
pd.set_option("display.max_columns", None)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [2]:
df = pd.read_csv("../data/raw/multi_touch_attribution_data.csv")

In [3]:
df.shape

(10000, 5)

In [4]:
df.head()

   User ID            Timestamp         Channel            Campaign Conversion
0    83281  2025-02-10 07:58:51           Email  New Product Launch         No
1    68071  2025-02-10 23:38:48      Search Ads         Winter Sale         No
2    90131  2025-02-11 10:41:07    Social Media     Brand Awareness        Yes
3    71026  2025-02-10 08:19:44  Direct Traffic                   -        Yes
4    94486  2025-02-10 15:15:46           Email         Retargeting        Yes

In [5]:
df.columns

Index(['User ID', 'Timestamp', 'Channel', 'Campaign', 'Conversion'], dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   User ID     10000 non-null  int64
 1   Timestamp   10000 non-null  str
 2   Channel     10000 non-null  str
 3   Campaign    10000 non-null  str
 4   Conversion  10000 non-null  str
dtypes: int64(1), str(4)
memory usage: 390.8 KB

In [8]:
attribution = pd.read_csv("../data/raw/multi_touch_attribution_data.csv")

performance = pd.read_csv("../data/raw/tech_advertising_campaigns_dataset.csv")

In [9]:
attribution.shape
performance.shape

(10000, 41)

In [10]:
attribution.head()
performance.head()

,campaign_id,campaign_objective,platform,ad_placement,device_type,operating_system,creative_format,creative_size,ad_copy_length,has_call_to_action,creative_emotion,creative_age_days,target_audience_age,target_audience_gender,audience_interest_category,income_bracket,purchase_intent_score,retargeting_flag,start_date,quarter,day_of_week,hour_of_day,campaign_day,quality_score,actual_cpc,impressions,clicks,conversions,ad_spend,revenue,bounce_rate,avg_session_duration_seconds,pages_per_session,industry_vertical,budget_tier,CTR,CPC,conversion_rate,CPA,ROAS,profit
0,CAMP_00001,Lead Generation,Facebook,Search,Mobile,Android,Text,728x90,Short,False,Curiosity,72,45-54,Female,Shoppers,<$50K,Medium,False,2024-03-06,1,Wednesday,18,34,5,2.23,66329,402,2,896.46,289.67,67.75,70,2.00,E-commerce,High,0.606,2.23,0.498,448.23,0.32,-606.79
1,CAMP_00002,Engagement,Facebook,Feed,Mobile,iOS,Image,320x50,Long,True,Neutral,62,65+,Female,Business Professionals,$50K-$100K,Medium,False,2024-01-26,1,Friday,6,22,5,2.48,50094,467,5,1158.16,1728.20,63.73,105,2.74,Finance,Medium,0.932,2.48,1.071,231.63,1.49,570.04
2,CAMP_00003,Conversions,Google Ads,Feed,Tablet,iOS,Video,1920x1080,Short,False,Urgency,79,65+,Male,Tech Enthusiasts,<$50K,High,False,2025-05-15,2,Thursday,1,32,4,3.88,10842,112,6,434.56,2903.26,31.93,149,3.97,Healthcare,Low,1.033,3.88,5.357,72.43,6.68,2468.70
3,CAMP_00004,Conversions,LinkedIn,Search,Desktop,iOS,Carousel,1920x1080,Short,False,Joy,57,35-44,All,Shoppers,<$50K,Low,False,2024-07-21,3,Sunday,7,32,4,8.29,7820,123,3,1019.67,502.28,65.52,147,2.49,Education,Medium,1.573,8.29,2.439,339.89,0.49,-517.39
4,CAMP_00005,Brand Awareness,Facebook,Stories,Mobile,iOS,Image,1920x1080,Short,False,Joy,17,25-34,Female,Students,$100K-$200K,Low,False,2025-03-09,1,Sunday,17,52,7,1.41,21436,302,0,425.82,0.00,68.95,81,3.04,SaaS,Low,1.409,1.41,0.000,0.00,0.00,-425.82

In [11]:
attribution.columns
performance.columns

Index(['campaign_id', 'campaign_objective', 'platform', 'ad_placement',
       'device_type', 'operating_system', 'creative_format', 'creative_size',
       'ad_copy_length', 'has_call_to_action', 'creative_emotion',
       'creative_age_days', 'target_audience_age', 'target_audience_gender',
       'audience_interest_category', 'income_bracket', 'purchase_intent_score',
       'retargeting_flag', 'start_date', 'quarter', 'day_of_week',
       'hour_of_day', 'campaign_day', 'quality_score', 'actual_cpc',
       'impressions', 'clicks', 'conversions', 'ad_spend', 'revenue',
       'bounce_rate', 'avg_session_duration_seconds', 'pages_per_session',
       'industry_vertical', 'budget_tier', 'CTR', 'CPC', 'conversion_rate',
       'CPA', 'ROAS', 'profit'],
      dtype='str')

In [12]:
attribution.info()
performance.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   User ID     10000 non-null  int64
 1   Timestamp   10000 non-null  str
 2   Channel     10000 non-null  str
 3   Campaign    10000 non-null  str
 4   Conversion  10000 non-null  str
dtypes: int64(1), str(4)
memory usage: 390.8 KB
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 41 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   campaign_id                   10000 non-null  str
 1   campaign_objective            10000 non-null  str
 2   platform                      10000 non-null  str
 3   ad_placement                  10000 non-null  str
 4   device_type                   10000 non-null  str
 5   operating_system              10000 non-null  str
 6   creative_format               10000 non-null  str
 7   creative_size                 10000 non-null  str
 8   ad_copy_length                10000 non-null  str
 9   has_call_to_action            10000 non-null  bool
 10  creative_emotion              10000 non-null  str
 11  creative_age_days             10000 non-null  int64
 12  target_audience_age           10000 non-null  str
 13  target_audience_gender        10000 non-null  str
 14  audience_interest_category    10000 non-null  str
 15  income_bracket                10000 non-null  str
 16  purchase_intent_score         10000 non-null  str
 17  retargeting_flag              10000 non-null  bool
 18  start_date                    10000 non-null  str
 19  quarter                       10000 non-null  int64
 20  day_of_week                   10000 non-null  str
 21  hour_of_day                   10000 non-null  int64
 22  campaign_day                  10000 non-null  int64
 23  quality_score                 10000 non-null  int64
 24  actual_cpc                    10000 non-null  float64
 25  impressions                   10000 non-null  int64
 26  clicks                        10000 non-null  int64
 27  conversions                   10000 non-null  int64
 28  ad_spend                      10000 non-null  float64
 29  revenue                       10000 non-null  float64
 30  bounce_rate                   10000 non-null  float64
 31  avg_session_duration_seconds  10000 non-null  int64
 32  pages_per_session             10000 non-null  float64
 33  industry_vertical             10000 non-null  str
 34  budget_tier                   10000 non-null  str
 35  CTR                           10000 non-null  float64
 36  CPC                           10000 non-null  float64
 37  conversion_rate               10000 non-null  float64
 38  CPA                           10000 non-null  float64
 39  ROAS                          10000 non-null  float64
 40  profit                        10000 non-null  float64
dtypes: bool(2), float64(11), int64(9), str(19)
memory usage: 3.0 MB